name: Release binary
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date +'%Y-%m-%d %H:%M:%S') >> ${GITHUB_ENV}
      - uses: wangyoucao577/go-release-action@v1.46
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          build_flags: -v
          binary_name: "lsf"
          extra_files: contrib README.md LICENSE.txt
          ldflags: -X "github.com/nv4d1k/live-stream-forwarder/global.Version=${{ env.APP_VERSION }}" -X "github.com/nv4d1k/live-stream-forwarder/global.BuildTime=${{ env.BUILD_TIME }}" -X github.com/nv4d1k/live-stream-forwarder/global.GitCommit=${{ github.sha }}
